version: '3.7' 

services:
  mongo:
    build: . 
    hostname: mongo
    user: root
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: stackoverflow
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db-volume:/data/mongo/db/
      - ./data/:/usr/local/share/
    networks:
      - my-network

  spark-master:
    image: bitnami/spark:3.4.1
    user: root
    hostname: spark
    environment:
      SPARK_MODE: master
    ports:
      - "8181:8080"
      - "9999:9999"
    volumes:
      - ./script/:/usr/local/share/spark/
      - ./data:/usr/local/share/data/
    networks:
      - my-network    


  spark-worker-a:
    image: bitnami/spark:3.4.1
    user: root
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    networks:
      - my-network   
  spark-worker-b:
    image: bitnami/spark:3.4.1
    user: root
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    networks:
      - my-network   
    
  kafka:
    image: 'bitnami/kafka:3.3.2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./data:/usr/local/share/data/
    networks:
      - my-network      
volumes:
  mongo-db-volume:

networks:
  my-network:
